### ISSUE TITLE
You code has a Stored-XSS Vulnerability in the backstage

### ISSUE THREAD

**Issue by zhouxingixng** [peacexie/imcat#1]
1、Login the backstage
http://127.0.0.1/root/run/adm.php

![default](https://user-images.githubusercontent.com/17960284/50955438-1a759500-14f4-11e9-9504-6d99e811e724.png)

payload：fm[instop][note]='"/></script><script>alert(1)</script>

fix：
1. Strictly verify user input, you must perform strict checks and html escape escaping on all input scripts, iframes, etc. The input here is not only the input interface that the user can directly interact with, but also the variables in the HTTP request in the HTTP request, the variables in the HTTP request header, and so on.
2. Verify the data type and verify its format, length, scope, and content.
3. Not only need to be verified on the client side but also on the server side.
4. The output data should also be checked. The values in the database may be output in multiple places on a large website. Even if the input is coded, the security check should be performed at the output points.

**Comment by peacexie** [comment]
Yes, It's ture has this bug(s), I'll fix them after NEXT version!

**Comment by peacexie** [comment]
git:440@2019-01-10
Fix:Stored-XSS Vulnerability(in the backstage)
https://github.com/peacexie/imcat/commit/b34dc3ac1355e14c2f73f5d6f19909409be921a4

**Comment by peacexie** [comment]
Maybe some other place has this bug too?
I'll check them carefully at the NEXT edition.
