### ISSUE TITLE
You code has a Code Execution Vulnerability in the backstage 

### ISSUE THREAD

**Issue by 876054426** [peacexie/imcat#3]
1、Login the backstage
http://127.0.0.1/root/run/adm.php

2.find “DIY配置”
http://127.0.0.1/root/run/adm.php?admin-ediy&part=exdiy

3 Click on the “修改”
![image](https://user-images.githubusercontent.com/38218756/74120763-a9754500-4bff-11ea-8948-d35121d376ee.png)

4 Modify the content payload：<?php   phpinfo(); ?>    And save it
![image](https://user-images.githubusercontent.com/38218756/74120815-dcb7d400-4bff-11ea-9964-a8eaf70d7860.png)

5 Access to this file  and it has a Code Execution
![image](https://user-images.githubusercontent.com/38218756/74120849-040ea100-4c00-11ea-848b-0b66cc8f9304.png)

fix:
1.The best removal of this function

**Comment by peacexie** [comment]
1. Fix as this:
https://github.com/peacexie/imcat/commit/3e914f61b7bfc3fca11175860333abc1321a14a9

2. By the way:
It only the administrator can edit this page!
