### ISSUE TITLE
The background management of imcat 5.3 has a getshell vulnerability

### ISSUE THREAD

**Issue by VllTomFord-0** [peacexie/imcat#6]
## 1. Environment construction

Source download: https://github.com/peacexie/imcat/releases

![image](https://user-images.githubusercontent.com/49917063/106357172-63008500-633f-11eb-9373-5da5140e43d8.png)

Environmental requirements:Apache 2.4.39 + php 7.3.4 + mysql 5.7.26

## 2. Vulnerability verification

As shown in the figure below, users can click "Tools->DIY Configuration->DIY Configuration" to edit the website PHP files.

![image](https://user-images.githubusercontent.com/49917063/106357202-96dbaa80-633f-11eb-859d-5191bafd94b7.png)

Try to write PHP webshell, as shown in the figure:

![image](https://user-images.githubusercontent.com/49917063/106357219-b377e280-633f-11eb-9e00-e2ed9b40b658.png)

Save and find that the system reports an error, as shown in the figure:

![image](https://user-images.githubusercontent.com/49917063/106357229-c5f21c00-633f-11eb-8464-ab92964aebb6.png)

At this point, it can be found that the system has a PHP file for security verification, and the eval() dangerous function exists in the PHP webshell, which causes the editing to fail. Find a PHP file upload code on Github (https://github.com/Allen-Liang/backup-for-php/edit/master/backup.php), modify the bootskip.php file to the PHP file upload code.

Visit at this time:http://10.211.55.9:83/root/cfgs/boot/bootskip.php

![image](https://user-images.githubusercontent.com/49917063/106357252-f8037e00-633f-11eb-9564-c4ffaa075156.png)

username:username  password：yourpassword

![image](https://user-images.githubusercontent.com/49917063/106357263-06519a00-6340-11eb-8c5b-bf08639dd8bf.png)

Any file can be uploaded at this time, including PHP webshell. as the picture shows:

![image](https://user-images.githubusercontent.com/49917063/106357497-5d0ba380-6341-11eb-8c8a-f7aadcbc7f29.png)

Visit the url of webshell, as shown in the figure:

![image](https://user-images.githubusercontent.com/49917063/106357295-313bee00-6340-11eb-92bf-d3538c49a926.png)

## 3. Vulnerability analysis

Analyze the system imcat/core/glib/safScan.php file, in which some functions with Webshell features are defined.

![image](https://user-images.githubusercontent.com/49917063/106357309-49137200-6340-11eb-899c-9dfb773ce24c.png)

However, after modifying the PHP file to other scripting languages and functions other than the dangerous function defined for this file, this file will not be intercepted, causing the attacker to modify the PHP file as a file upload function, and then upload the Webshell on this basis. You can get the permissions of the web application.

**Comment by peacexie** [comment]
Yes, the administrator can modify any file,
Just like he/she can delete anything...
But I don't want to disable this function. What should I do?

**Comment by VllTomFord-0** [comment]
You can delete or disable this function module.

**Comment by peacexie** [comment]
I'll set a switch in the next version, It is disabled by default.

**Comment by VllTomFord-0** [comment]
OK, Thanks!
Can you help me requests a CVE？
[Requesting a CVE identification number-GitHub Docs](https://docs.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory#requesting-a-cve-identification-number)
![image](https://user-images.githubusercontent.com/49917063/106387332-4f731e00-6414-11eb-8fcd-b17d088177b2.png)


Thinks.

**Comment by peacexie** [comment]
Ow...You dig this so called bug, 
It is just for `Requesting a CVE identification number`?
Ok, I will publish a security advisory... for this!
