### ISSUE TITLE
imcat 5.2-Arbitrary file read vulnerability

### ISSUE THREAD

**Issue by haungtongfu** [peacexie/imcat#7]
1 ### Overview

Official website: http://txjia.com/imcat/

Version: imcat-5.2

Vulnerability type: arbitrary file reading, causing serious information leakage

Source code：https://github.com/peacexie/imcat/releases/tag/v5.2

2. Source code ### analysis

In the file root tools adbug search.php, click$_ Request receives parameters from the front end and uses file directly without any filtering_ get_ The contents() function gets the contents of the file and prints them directly on the front page; It can jump to the previous directory by the way of "." / ", as long as the program has permission, it can read any file on the system, causing information leakage; The specific code is shown in the following two figures.

![1qa](https://user-images.githubusercontent.com/58809869/122016773-ec4abc80-cdf3-11eb-8c5b-a777ebf52247.png)

![image](https://user-images.githubusercontent.com/58809869/122016844-fec4f600-cdf3-11eb-84bc-c88620cf4e9a.png)

3. ### Reappearance

(1) Build the environment through phpstudy, and then log in to the background of the website
![image](https://user-images.githubusercontent.com/58809869/122016958-2025e200-cdf4-11eb-9b38-998961707164.png)

(2) Visit the following links (you can construct whatever files you want to get, and you can also get system files by ". /" tracing back)
http://127.0.0.1/imcat/root/tools/adbug/search.php?act=View&file= \root\cfgs\boot\cfg_ db.php
![image](https://user-images.githubusercontent.com/58809869/122017085-3c298380-cdf4-11eb-9082-df67a0926afc.png)

http://127.0.0.1/imcat/root/tools/adbug/search.php?act=View&file=../../../../../../test.txt
![image](https://user-images.githubusercontent.com/58809869/122017130-477caf00-cdf4-11eb-8ddd-8ee528ba90f5.png)

**Comment by peacexie** [comment]
1. As an adminstrator, It(He/She) cant use the File-Search tool; 
The guest are NOT allowed to use this function.

2. You can use imcat-v5.5, I am fixed it at v5.4,
It was disabled by default at v5.4.

**Comment by haungtongfu** [comment]
This vulnerability is still present in v5.4 and v5.5 versions

**Comment by peacexie** [comment]
@haungtongfu 
Sorry!
Fix is as this commit :
1. File: root/tools/adbug/search.php
2. Code: https://github.com/peacexie/imcat/commit/b1c90b577b6c0e3d196d61406b6d663096968de2

**Comment by peacexie** [comment]
Sorry!
The DIY-mode, It was disabled by default only at `master branch`.
In v5.4, this feature was not update.
